
CREATE DATABASE IF NOT EXISTS NomadaSyncDB;
USE NomadaSyncDB;


CREATE TABLE Usuarios (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Usuario VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    AvatarIniciales VARCHAR(5),
    FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Viajes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(150) NOT NULL,
    Ubicacion VARCHAR(100),
    FechaInicio DATE,
    FechaFin DATE,
    Estado VARCHAR(20) DEFAULT 'Activo', 
    CreadorId INT NOT NULL,
    FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CreadorId) REFERENCES Usuarios(Id) ON DELETE CASCADE
);

CREATE TABLE Amigos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioId INT NOT NULL,
    AmigoId INT NOT NULL,
    FechaAmistad TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UsuarioId) REFERENCES Usuarios(Id) ON DELETE CASCADE,
    FOREIGN KEY (AmigoId) REFERENCES Usuarios(Id) ON DELETE CASCADE
);


CREATE TABLE ParticipanteViaje (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioId INT NOT NULL,
    ViajeId INT NOT NULL,
    Presupuesto DECIMAL(10,2) DEFAULT 0,
    FOREIGN KEY (UsuarioId) REFERENCES Usuarios(Id) ON DELETE CASCADE,
    FOREIGN KEY (ViajeId) REFERENCES Viajes(Id) ON DELETE CASCADE
);



CREATE TABLE Gastos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ViajeId INT NOT NULL,
    UsuarioId INT NOT NULL,
    Categoria VARCHAR(50),
    Descripcion VARCHAR(255),
    Monto DECIMAL(10,2) NOT NULL,
    Modalidad VARCHAR(20) DEFAULT 'Equal', 
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ViajeId) REFERENCES Viajes(Id) ON DELETE CASCADE,
    FOREIGN KEY (UsuarioId) REFERENCES Usuarios(Id) ON DELETE CASCADE
);


CREATE TABLE GastosDetalles (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    GastoId INT NOT NULL,
    UsuarioId INT NOT NULL,
    Porcentaje DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (GastoId) REFERENCES Gastos(Id) ON DELETE CASCADE,
    FOREIGN KEY (UsuarioId) REFERENCES Usuarios(Id) ON DELETE CASCADE
);


CREATE TABLE Notificaciones (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UsuarioId INT NOT NULL,
    Mensaje VARCHAR(255) NOT NULL,
    Leida BOOLEAN DEFAULT FALSE,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UsuarioId) REFERENCES Usuarios(Id) ON DELETE CASCADE
);


CREATE TABLE Liquidaciones (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ViajeId INT NOT NULL,
    DeudorId INT NOT NULL,
    AcreedorId INT NOT NULL,
    Monto DECIMAL(10,2) NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ViajeId) REFERENCES Viajes(Id) ON DELETE CASCADE,
    FOREIGN KEY (DeudorId) REFERENCES Usuarios(Id) ON DELETE CASCADE,
    FOREIGN KEY (AcreedorId) REFERENCES Usuarios(Id) ON DELETE CASCADE
);
